// <auto-generated />
namespace Smoelenboek.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class foreignkey_student : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(foreignkey_student));
        
        string IMigrationMetadata.Id
        {
            get { return "201609290958033_foreignkey_student"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
